name: CI QuickBite

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Install backend dependencies
        run: cd backend && npm ci

      - name: 4. Lint backend
        run: cd backend && npm run lint

      - name: 5. Test backend
        run: cd backend && npm test

      - name: 6. Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: 7. Build Docker backend
        run: docker build -t rouakhribiche/quickbite-backend:latest ./backend

      - name: 8. Push Docker backend
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u rouakhribiche --password-stdin
          docker push rouakhribiche/quickbite-backend:latest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Install frontend dependencies
        run: cd frontend && npm ci

      - name: 4. Lint frontend
        run: cd frontend && npm run lint

      - name: 5. Test frontend
        run: cd frontend && npm test

      - name: 6. Build frontend
        run: cd frontend && npm run build

      - name: 7. Build Docker frontend
        run: docker build -t rouakhribiche/quickbite-frontend:latest ./frontend

      - name: 8. Push Docker frontend
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u rouakhribiche --password-stdin
          docker push rouakhribiche/quickbite-frontend:latest